### ISSUE TITLE
Section Delegation

### ISSUE THREAD

**Issue by ghost** [mozilla/open-leadership-training-series#65]
I don't remember reading about delegation, but if it's already in, please close this request.  

But this section is really more for when the current leader retires and needs to pass on the leadership on to the next person who is ready.  Of course in other places where delegation is needed.

If possible, I'm willing to make a pull request to add my [sustaining-it ](https://github.com/belkinsa/open-leadership-training-series/tree/sustaining-it) branch to the main repo where these experimental sections can be written.  Or I can work with those who want to write these in my own fork and then make the requests myself.

**Comment by zee-moz** [comment]
@belkinsa hi! thanks for opening this issue. there's a small section on ["distributed leadership"](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/understand-meaningful-participation-and-distributed-leadership/) here, in the building communities section.  It ended up there because it's about growing lasting participation. If I remember correctly I think we avoided the term "delegation" because it felt a little too much like a manager-term, but that's up for debate.  What would you add, or change, and where do you think this section should live?

**Comment by ghost** [comment]
That's the section that I was thinking of, thank you!  And I think it's fine the way it is.
